mock matchers › failing output › expect.mock.not.toThrow single exception
<dim>expect.mock(</resetDimAndBold><red>mock</resetColor><dim>).</resetDimAndBold>not<dim>toThrow(</resetDimAndBold><dim>)</resetDimAndBold>

Expected the function not to throw an error.
Instead, it threw: 
  <red>Not_found</resetColor>
